export const april = [
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
  
  {
    date: "2025-04-01",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "रेवती",
    sunrise: "06:11 AM",
    sunset: "06:59 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-02",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "अश्विनी",
    sunrise: "06:10 AM",
    sunset: "07:00 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-03",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "भरणी",
    sunrise: "06:09 AM",
    sunset: "07:01 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-04",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "कृत्तिका",
    sunrise: "06:08 AM",
    sunset: "07:02 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-05",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "रोहिणी",
    sunrise: "06:07 AM",
    sunset: "07:03 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-06",
    title: "Durga Ashtami (Navratri Day 8)",
    description: "Worship of Goddess Durga",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "मृगशिरा",
    sunrise: "06:06 AM",
    sunset: "07:04 PM",
    event: true,
    url: "/other/durga.png"
  },
  {
    date: "2025-04-07",
    title: "Ram Navami",
    description: "Birthday of Lord Rama",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "आर्द्रा",
    sunrise: "06:05 AM",
    sunset: "07:05 PM",
    event: true,
    url: "/other/ramnavami.png"
  },
  {
    date: "2025-04-08",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "पुनर्वसु",
    sunrise: "06:04 AM",
    sunset: "07:06 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-09",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "पुष्य",
    sunrise: "06:03 AM",
    sunset: "07:07 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-10",
    title: "Kamada Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "आश्लेषा",
    sunrise: "06:02 AM",
    sunset: "07:08 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-04-11",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "मघा",
    sunrise: "06:01 AM",
    sunset: "07:09 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-12",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "06:00 AM",
    sunset: "07:10 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-13",
    title: "Chaitra Purnima",
    description: "Full Moon Day",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "05:59 AM",
    sunset: "07:11 PM",
    event: true,
    url: "/other/fullmoon.png"
  },
  {
    date: "2025-04-14",
    title: "Mesh Sankranti / Baisakhi",
    description: "Harvest festival, Sun enters Aries",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "हस्त",
    sunrise: "05:58 AM",
    sunset: "07:12 PM",
    event: true,
    url: "/other/baisakhi.png"
  },
  {
    date: "2025-04-15",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "चित्रा",
    sunrise: "05:57 AM",
    sunset: "07:13 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-16",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "स्वाति",
    sunrise: "05:56 AM",
    sunset: "07:14 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-17",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "विशाखा",
    sunrise: "05:55 AM",
    sunset: "07:15 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-18",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "अनुराधा",
    sunrise: "05:54 AM",
    sunset: "07:16 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-19",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "ज्येष्ठा",
    sunrise: "05:53 AM",
    sunset: "07:17 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-20",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "मूल",
    sunrise: "05:52 AM",
    sunset: "07:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-21",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "05:51 AM",
    sunset: "07:19 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-22",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "05:50 AM",
    sunset: "07:20 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-23",
    title: "Varuthini Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "श्रवण",
    sunrise: "05:49 AM",
    sunset: "07:21 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-04-24",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "धनिष्ठा",
    sunrise: "05:48 AM",
    sunset: "07:22 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-25",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "शतभिषा",
    sunrise: "05:47 AM",
    sunset: "07:23 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-26",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "05:46 AM",
    sunset: "07:24 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-27",
    title: "Vaishakha Amavasya",
    description: "No Moon Day",
    hinduMonth: "वैशाख",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "05:45 AM",
    sunset: "07:25 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-04-28",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "रेवती",
    sunrise: "05:44 AM",
    sunset: "07:26 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-29",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "अश्विनी",
    sunrise: "05:43 AM",
    sunset: "07:27 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-04-30",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "भरणी",
    sunrise: "05:42 AM",
    sunset: "07:28 PM",
    event: false,
    url: ""
  }
];