export const august = [
  {
    date: "2025-08-01",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "विशाखा",
    sunrise: "05:26 AM",
    sunset: "08:03 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-02",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "अनुराधा",
    sunrise: "05:26 AM",
    sunset: "08:02 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-03",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "ज्येष्ठा",
    sunrise: "05:27 AM",
    sunset: "08:01 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-04",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "मूल",
    sunrise: "05:27 AM",
    sunset: "08:00 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-05",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "05:28 AM",
    sunset: "07:59 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-06",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "05:28 AM",
    sunset: "07:58 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-07",
    title: "Kamika Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "श्रवण",
    sunrise: "05:29 AM",
    sunset: "07:57 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-08-08",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "धनिष्ठा",
    sunrise: "05:29 AM",
    sunset: "07:56 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-09",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "शतभिषा",
    sunrise: "05:30 AM",
    sunset: "07:55 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-10",
    title: "Shravana Purnima (Raksha Bandhan)",
    description: "Full Moon Day, Raksha Bandhan",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "05:30 AM",
    sunset: "07:54 PM",
    event: true,
    url: "/other/rakhi.png"
  },
  {
    date: "2025-08-11",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "05:31 AM",
    sunset: "07:53 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-12",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "रेवती",
    sunrise: "05:31 AM",
    sunset: "07:52 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-13",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "अश्विनी",
    sunrise: "05:32 AM",
    sunset: "07:51 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-14",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "भरणी",
    sunrise: "05:32 AM",
    sunset: "07:50 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-15",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "कृत्तिका",
    sunrise: "05:33 AM",
    sunset: "07:49 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-16",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "रोहिणी",
    sunrise: "05:33 AM",
    sunset: "07:48 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-17",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "मृगशिरा",
    sunrise: "05:34 AM",
    sunset: "07:47 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-18",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "आर्द्रा",
    sunrise: "05:34 AM",
    sunset: "07:46 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-19",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "पुनर्वसु",
    sunrise: "05:35 AM",
    sunset: "07:45 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-20",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "पुष्य",
    sunrise: "05:35 AM",
    sunset: "07:44 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-21",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "आश्लेषा",
    sunrise: "05:36 AM",
    sunset: "07:43 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-22",
    title: "Aja Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "मघा",
    sunrise: "05:36 AM",
    sunset: "07:42 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-08-23",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "05:37 AM",
    sunset: "07:41 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-24",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "05:37 AM",
    sunset: "07:40 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-25",
    title: "Bhadrapada Amavasya",
    description: "No Moon Day",
    hinduMonth: "भाद्रपद",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "हस्त",
    sunrise: "05:38 AM",
    sunset: "07:39 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-08-26",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "चित्रा",
    sunrise: "05:38 AM",
    sunset: "07:38 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-27",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "स्वाति",
    sunrise: "05:39 AM",
    sunset: "07:37 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-28",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "विशाखा",
    sunrise: "05:39 AM",
    sunset: "07:36 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-29",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "अनुराधा",
    sunrise: "05:40 AM",
    sunset: "07:35 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-30",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "ज्येष्ठा",
    sunrise: "05:40 AM",
    sunset: "07:34 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-08-31",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "मूल",
    sunrise: "05:41 AM",
    sunset: "07:33 PM",
    event: false,
    url: ""
  }
];