export const december = [
  {
    date: "2025-12-01",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "कृत्तिका",
    sunrise: "06:27 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-02",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "रोहिणी",
    sunrise: "06:27 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-03",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "मृगशिरा",
    sunrise: "06:28 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-04",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "आर्द्रा",
    sunrise: "06:28 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-05",
    title: "Mokshada Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "पुनर्वसु",
    sunrise: "06:29 AM",
    sunset: "06:18 PM",
    event: true,
    url: "/other/ekadashi.png",
  },
  {
    date: "2025-12-06",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "पुष्य",
    sunrise: "06:29 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-07",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "आश्लेषा",
    sunrise: "06:30 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-08",
    title: "Margashirsha Purnima",
    description: "Full Moon Day",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "मघा",
    sunrise: "06:30 AM",
    sunset: "06:18 PM",
    event: true,
    url: "/other/fullmoon.png",
  },
  {
    date: "2025-12-09",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "06:31 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-10",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "06:31 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-11",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "हस्त",
    sunrise: "06:32 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-12",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "चित्रा",
    sunrise: "06:32 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-13",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "स्वाति",
    sunrise: "06:33 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-14",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "विशाखा",
    sunrise: "06:33 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-15",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "अनुराधा",
    sunrise: "06:34 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-16",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "ज्येष्ठा",
    sunrise: "06:34 AM",
    sunset: "06:18 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-17",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "मूल",
    sunrise: "06:35 AM",
    sunset: "06:19 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-18",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "06:35 AM",
    sunset: "06:19 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-19",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "06:36 AM",
    sunset: "06:19 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-20",
    title: "Saphala Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "श्रवण",
    sunrise: "06:36 AM",
    sunset: "06:19 PM",
    event: true,
    url: "/other/ekadashi.png",
  },
  {
    date: "2025-12-21",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "धनिष्ठा",
    sunrise: "06:37 AM",
    sunset: "06:19 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-22",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "शतभिषा",
    sunrise: "06:37 AM",
    sunset: "06:20 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-23",
    title: "Paush Amavasya",
    description: "No Moon Day",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "06:38 AM",
    sunset: "06:20 PM",
    event: true,
    url: "/other/nomoon.png",
  },
  {
    date: "2025-12-24",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "06:38 AM",
    sunset: "06:20 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-25",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "रेवती",
    sunrise: "06:39 AM",
    sunset: "06:21 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-26",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "अश्विनी",
    sunrise: "06:39 AM",
    sunset: "06:21 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-27",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "भरणी",
    sunrise: "06:40 AM",
    sunset: "06:21 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-28",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "कृत्तिका",
    sunrise: "06:40 AM",
    sunset: "06:22 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-29",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "रोहिणी",
    sunrise: "06:41 AM",
    sunset: "06:22 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-30",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "मृगशिरा",
    sunrise: "06:41 AM",
    sunset: "06:23 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-12-31",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "आर्द्रा",
    sunrise: "06:42 AM",
    sunset: "06:23 PM",
    event: false,
    url: "",
  },
];
