export const february = [
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
  {
    date: "2025-02-01",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "श्रवण",
    sunrise: "07:09 AM",
    sunset: "06:00 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-02",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "धनिष्ठा",
    sunrise: "07:08 AM",
    sunset: "06:01 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-03",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "शतभिषा",
    sunrise: "07:08 AM",
    sunset: "06:02 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-04",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "07:07 AM",
    sunset: "06:03 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-05",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "07:06 AM",
    sunset: "06:04 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-06",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "रेवती",
    sunrise: "07:05 AM",
    sunset: "06:05 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-07",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "अश्विनी",
    sunrise: "07:04 AM",
    sunset: "06:06 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-08",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "भरणी",
    sunrise: "07:03 AM",
    sunset: "06:07 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-09",
    title: "Jaya Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "कृत्तिका",
    sunrise: "07:02 AM",
    sunset: "06:08 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-02-10",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "रोहिणी",
    sunrise: "07:01 AM",
    sunset: "06:09 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-11",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "मृगशिरा",
    sunrise: "07:00 AM",
    sunset: "06:10 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-12",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "आर्द्रा",
    sunrise: "06:59 AM",
    sunset: "06:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-13",
    title: "Magha Purnima",
    description: "Full Moon Day",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "पुनर्वसु",
    sunrise: "06:58 AM",
    sunset: "06:12 PM",
    event: true,
    url: "/other/fullmoon.png"
  },
  {
    date: "2025-02-14",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पुष्य",
    sunrise: "06:57 AM",
    sunset: "06:13 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-15",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "आश्लेषा",
    sunrise: "06:56 AM",
    sunset: "06:14 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-16",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "मघा",
    sunrise: "06:55 AM",
    sunset: "06:15 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-17",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "06:54 AM",
    sunset: "06:16 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-18",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "06:53 AM",
    sunset: "06:17 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-19",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "हस्त",
    sunrise: "06:52 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-20",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "चित्रा",
    sunrise: "06:51 AM",
    sunset: "06:19 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-21",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "स्वाति",
    sunrise: "06:50 AM",
    sunset: "06:20 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-22",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "विशाखा",
    sunrise: "06:49 AM",
    sunset: "06:21 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-23",
    title: "Vijaya Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "अनुराधा",
    sunrise: "06:48 AM",
    sunset: "06:22 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-02-24",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "ज्येष्ठा",
    sunrise: "06:47 AM",
    sunset: "06:23 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-25",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "मूल",
    sunrise: "06:46 AM",
    sunset: "06:24 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-26",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "06:45 AM",
    sunset: "06:25 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-27",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "06:44 AM",
    sunset: "06:26 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-02-28",
    title: "Phalguna Amavasya",
    description: "No Moon Day",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "अमावस्या",
    nakshatra: "श्रवण",
    sunrise: "06:43 AM",
    sunset: "06:27 PM",
    event: true,
    url: "/other/nomoon.png"
  }
];