export const january = [
  {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
  {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
  {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
  {
    date: "2025-01-01",
    title: "New Year’s Day",
    description: "Celebration of the New Year",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "07:14 AM",
    sunset: "05:34 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-02",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "श्रवण",
    sunrise: "07:14 AM",
    sunset: "05:35 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-03",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "श्रवण",
    sunrise: "07:14 AM",
    sunset: "05:36 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-04",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "धनिष्ठा",
    sunrise: "07:14 AM",
    sunset: "05:36 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-05",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "शतभिषा",
    sunrise: "07:14 AM",
    sunset: "05:37 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-06",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "07:14 AM",
    sunset: "05:38 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-07",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "07:14 AM",
    sunset: "05:38 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-08",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "रेवती",
    sunrise: "07:14 AM",
    sunset: "05:39 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-09",
    title: "Saphala Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "अश्विनी",
    sunrise: "07:14 AM",
    sunset: "05:40 PM",
    event: true,
    url: "",
  },
  {
    date: "2025-01-10",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "भरणी",
    sunrise: "07:14 AM",
    sunset: "05:41 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-11",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "कृत्तिका",
    sunrise: "07:14 AM",
    sunset: "05:41 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-12",
    title: "Swami Vivekananda Jayanti",
    description: "National Youth Day",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "रोहिणी",
    sunrise: "07:14 AM",
    sunset: "05:42 PM",
    event: true,
    url: "/other/vivek.png",
  },
  {
    date: "2025-01-13",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "मृगशिरा",
    sunrise: "07:14 AM",
    sunset: "05:43 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-14",
    title: "Makar Sankranti",
    description: "Harvest festival, Sun enters Capricorn",
    hinduMonth: "पौष",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "आर्द्रा",
    sunrise: "07:14 AM",
    sunset: "05:44 PM",
    event: true,
    url: "/other/makar-sankranti.png",
  },
  {
    date: "2025-01-15",
    title: "Pongal",
    description: "Tamil Nadu harvest festival",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पुनर्वसु",
    sunrise: "07:14 AM",
    sunset: "05:44 PM",
    event: true,
    url: "",
  },
  {
    date: "2025-01-16",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "पुष्य",
    sunrise: "07:14 AM",
    sunset: "05:45 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-17",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "आश्लेषा",
    sunrise: "07:14 AM",
    sunset: "05:46 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-18",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "मघा",
    sunrise: "07:14 AM",
    sunset: "05:47 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-19",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "07:14 AM",
    sunset: "05:47 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-20",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "07:14 AM",
    sunset: "05:48 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-21",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "हस्त",
    sunrise: "07:13 AM",
    sunset: "05:49 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-22",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "चित्रा",
    sunrise: "07:13 AM",
    sunset: "05:50 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-23",
    title: "Subhas Chandra Bose Jayanti",
    description: "Honoring the great freedom fighter",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "स्वाति",
    sunrise: "07:13 AM",
    sunset: "05:51 PM",
    event: true,
    url: "/other/bose.png",
  },
  {
    date: "2025-01-24",
    title: "Shattila Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "विशाखा",
    sunrise: "07:13 AM",
    sunset: "05:51 PM",
    event: true,
    url: "",
  },
  {
    date: "2025-01-25",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "अनुराधा",
    sunrise: "07:13 AM",
    sunset: "05:52 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-26",
    title: "Republic Day",
    description: "India's Constitution Day",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "ज्येष्ठा",
    sunrise: "07:12 AM",
    sunset: "05:53 PM",
    event: true,
    url: "/republicday.png",
  },
  {
    date: "2025-01-27",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "मूल",
    sunrise: "07:12 AM",
    sunset: "05:54 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-28",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "07:12 AM",
    sunset: "05:55 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-29",
    title: "",
    description: "",
    hinduMonth: "पौष",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "07:11 AM",
    sunset: "05:56 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-30",
    title: "",
    description: "",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "श्रवण",
    sunrise: "07:11 AM",
    sunset: "05:57 PM",
    event: false,
    url: "",
  },
  {
    date: "2025-01-31",
    title: "Magha Amavasya",
    description: "Important day for charity and spiritual practices",
    hinduMonth: "माघ",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "श्रवण",
    sunrise: "07:10 AM",
    sunset: "05:58 PM",
    event: true,
    url: "/other/nomoon.png",
  },
];
