export const july = [
  {
    date: "2025-07-01",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "05:10 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-02",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "हस्त",
    sunrise: "05:11 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-03",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "चित्रा",
    sunrise: "05:11 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-04",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "स्वाति",
    sunrise: "05:12 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-05",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "विशाखा",
    sunrise: "05:12 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-06",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "अनुराधा",
    sunrise: "05:13 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-07",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "ज्येष्ठा",
    sunrise: "05:13 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-08",
    title: "Devshayani Ekadashi",
    description: "Ekadashi Vrat, Vishnu Shayan",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "मूल",
    sunrise: "05:14 AM",
    sunset: "08:12 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-07-09",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "05:14 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-10",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "05:15 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-11",
    title: "Ashadha Purnima (Guru Purnima)",
    description: "Full Moon Day, Guru Purnima",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "श्रवण",
    sunrise: "05:15 AM",
    sunset: "08:12 PM",
    event: true,
    url: "/other/guru.png"
  },
  {
    date: "2025-07-12",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "धनिष्ठा",
    sunrise: "05:16 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-13",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "शतभिषा",
    sunrise: "05:16 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-14",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "05:17 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-15",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "05:17 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-16",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "रेवती",
    sunrise: "05:18 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-17",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "अश्विनी",
    sunrise: "05:18 AM",
    sunset: "08:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-18",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "भरणी",
    sunrise: "05:19 AM",
    sunset: "08:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-19",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "कृत्तिका",
    sunrise: "05:19 AM",
    sunset: "08:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-20",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "रोहिणी",
    sunrise: "05:20 AM",
    sunset: "08:10 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-21",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "मृगशिरा",
    sunrise: "05:20 AM",
    sunset: "08:10 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-22",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "आर्द्रा",
    sunrise: "05:21 AM",
    sunset: "08:09 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-23",
    title: "Shayani Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "पुनर्वसु",
    sunrise: "05:21 AM",
    sunset: "08:09 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-07-24",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "पुष्य",
    sunrise: "05:22 AM",
    sunset: "08:08 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-25",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "आश्लेषा",
    sunrise: "05:22 AM",
    sunset: "08:08 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-26",
    title: "Shravana Amavasya",
    description: "No Moon Day",
    hinduMonth: "श्रावण",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "मघा",
    sunrise: "05:23 AM",
    sunset: "08:07 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-07-27",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "05:23 AM",
    sunset: "08:07 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-28",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "05:24 AM",
    sunset: "08:06 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-29",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "हस्त",
    sunrise: "05:24 AM",
    sunset: "08:05 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-30",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "चित्रा",
    sunrise: "05:25 AM",
    sunset: "08:05 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-07-31",
    title: "",
    description: "",
    hinduMonth: "श्रावण",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "स्वाति",
    sunrise: "05:25 AM",
    sunset: "08:04 PM",
    event: false,
    url: ""
  }
];