export const june = [
  {
    date: "2025-06-01",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "आश्लेषा",
    sunrise: "05:10 AM",
    sunset: "08:00 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-02",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "मघा",
    sunrise: "05:10 AM",
    sunset: "08:01 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-03",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "05:09 AM",
    sunset: "08:02 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-04",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "05:09 AM",
    sunset: "08:02 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-05",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "हस्त",
    sunrise: "05:08 AM",
    sunset: "08:03 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-06",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "चित्रा",
    sunrise: "05:08 AM",
    sunset: "08:04 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-07",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "स्वाति",
    sunrise: "05:08 AM",
    sunset: "08:05 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-08",
    title: "Nirjala Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "विशाखा",
    sunrise: "05:07 AM",
    sunset: "08:05 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-06-09",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "अनुराधा",
    sunrise: "05:07 AM",
    sunset: "08:06 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-10",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "ज्येष्ठा",
    sunrise: "05:07 AM",
    sunset: "08:07 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-11",
    title: "Jyeshtha Purnima",
    description: "Full Moon Day",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "मूल",
    sunrise: "05:07 AM",
    sunset: "08:07 PM",
    event: true,
    url: "/other/fullmoon.png"
  },
  {
    date: "2025-06-12",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "05:07 AM",
    sunset: "08:08 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-13",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "05:07 AM",
    sunset: "08:08 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-14",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "श्रवण",
    sunrise: "05:07 AM",
    sunset: "08:09 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-15",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "धनिष्ठा",
    sunrise: "05:07 AM",
    sunset: "08:09 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-16",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "शतभिषा",
    sunrise: "05:07 AM",
    sunset: "08:10 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-17",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "05:07 AM",
    sunset: "08:10 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-18",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "05:07 AM",
    sunset: "08:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-19",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "रेवती",
    sunrise: "05:07 AM",
    sunset: "08:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-20",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "अश्विनी",
    sunrise: "05:07 AM",
    sunset: "08:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-21",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "भरणी",
    sunrise: "05:08 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-22",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "कृत्तिका",
    sunrise: "05:08 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-23",
    title: "Yogini Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "रोहिणी",
    sunrise: "05:08 AM",
    sunset: "08:12 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-06-24",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "मृगशिरा",
    sunrise: "05:08 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-25",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "आर्द्रा",
    sunrise: "05:08 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-26",
    title: "Ashadha Amavasya",
    description: "No Moon Day",
    hinduMonth: "आषाढ़",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "पुनर्वसु",
    sunrise: "05:09 AM",
    sunset: "08:12 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-06-27",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पुष्य",
    sunrise: "05:09 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-28",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "आश्लेषा",
    sunrise: "05:09 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-29",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "मघा",
    sunrise: "05:10 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-06-30",
    title: "",
    description: "",
    hinduMonth: "आषाढ़",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "05:10 AM",
    sunset: "08:12 PM",
    event: false,
    url: ""
  }
];