export const march = [
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
    {
    date: "",
    title: "",
    description: "",
    hinduMonth: "",
    paksh: "",
    tithi: "",
    nakshatra: "",
    sunrise: "",
    sunset: "",
    event: false,
    url: "",
  },
  {
    date: "2025-03-01",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "श्रवण",
    sunrise: "06:42 AM",
    sunset: "06:28 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-02",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "धनिष्ठा",
    sunrise: "06:41 AM",
    sunset: "06:29 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-03",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "शतभिषा",
    sunrise: "06:40 AM",
    sunset: "06:30 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-04",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "06:39 AM",
    sunset: "06:31 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-05",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "06:38 AM",
    sunset: "06:32 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-06",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "रेवती",
    sunrise: "06:37 AM",
    sunset: "06:33 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-07",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "अश्विनी",
    sunrise: "06:36 AM",
    sunset: "06:34 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-08",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "भरणी",
    sunrise: "06:35 AM",
    sunset: "06:35 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-09",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "कृत्तिका",
    sunrise: "06:34 AM",
    sunset: "06:36 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-10",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "रोहिणी",
    sunrise: "06:33 AM",
    sunset: "06:37 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-11",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "मृगशिरा",
    sunrise: "06:32 AM",
    sunset: "06:38 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-12",
    title: "Amalaki Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "आर्द्रा",
    sunrise: "06:31 AM",
    sunset: "06:39 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-03-13",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "पुनर्वसु",
    sunrise: "06:30 AM",
    sunset: "06:40 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-14",
    title: "",
    description: "",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "पुष्य",
    sunrise: "06:29 AM",
    sunset: "06:41 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-15",
    title: "Phalguna Purnima (Holi)",
    description: "Holi, Full Moon Day",
    hinduMonth: "फाल्गुन",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "आश्लेषा",
    sunrise: "06:28 AM",
    sunset: "06:42 PM",
    event: true,
    url: "/other/holi.png"
  },
  {
    date: "2025-03-16",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "मघा",
    sunrise: "06:27 AM",
    sunset: "06:43 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-17",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "06:26 AM",
    sunset: "06:44 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-18",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "06:25 AM",
    sunset: "06:45 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-19",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "हस्त",
    sunrise: "06:24 AM",
    sunset: "06:46 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-20",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "चित्रा",
    sunrise: "06:23 AM",
    sunset: "06:47 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-21",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "स्वाति",
    sunrise: "06:22 AM",
    sunset: "06:48 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-22",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "विशाखा",
    sunrise: "06:21 AM",
    sunset: "06:49 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-23",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "अनुराधा",
    sunrise: "06:20 AM",
    sunset: "06:50 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-24",
    title: "Papmochani Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "मूल",
    sunrise: "06:19 AM",
    sunset: "06:51 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-03-25",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "06:18 AM",
    sunset: "06:52 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-26",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "06:17 AM",
    sunset: "06:53 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-27",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "श्रवण",
    sunrise: "06:16 AM",
    sunset: "06:54 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-03-28",
    title: "Chaitra Amavasya",
    description: "No Moon Day",
    hinduMonth: "चैत्र",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "धनिष्ठा",
    sunrise: "06:15 AM",
    sunset: "06:55 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-03-29",
    title: "Chaitra Navratri Begins",
    description: "Start of Chaitra Navratri, Ghatasthapana",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "शतभिषा",
    sunrise: "06:14 AM",
    sunset: "06:56 PM",
    event: true,
    url: "/other/navratri.png"
  },
  {
    date: "2025-03-30",
    title: "Saraswati Puja (Navratri Day 2)",
    description: "Worship of Goddess Saraswati",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "06:13 AM",
    sunset: "06:57 PM",
    event: true,
    url: "/other/saraswati.png"
  },
  {
    date: "2025-03-31",
    title: "",
    description: "",
    hinduMonth: "चैत्र",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "06:12 AM",
    sunset: "06:58 PM",
    event: false,
    url: ""
  }
];