export const may = [
  {
    date: "2025-05-01",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "कृत्तिका",
    sunrise: "05:41 AM",
    sunset: "07:29 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-02",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "रोहिणी",
    sunrise: "05:40 AM",
    sunset: "07:30 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-03",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "मृगशिरा",
    sunrise: "05:39 AM",
    sunset: "07:31 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-04",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "आर्द्रा",
    sunrise: "05:38 AM",
    sunset: "07:32 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-05",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "पुनर्वसु",
    sunrise: "05:37 AM",
    sunset: "07:33 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-06",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "पुष्य",
    sunrise: "05:36 AM",
    sunset: "07:34 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-07",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "आश्लेषा",
    sunrise: "05:35 AM",
    sunset: "07:35 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-08",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "मघा",
    sunrise: "05:34 AM",
    sunset: "07:36 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-09",
    title: "Mohini Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "05:33 AM",
    sunset: "07:37 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-05-10",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "05:32 AM",
    sunset: "07:38 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-11",
    title: "",
    description: "",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "हस्त",
    sunrise: "05:31 AM",
    sunset: "07:39 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-12",
    title: "Vaishakha Purnima (Buddha Purnima)",
    description: "Full Moon Day, Buddha Jayanti",
    hinduMonth: "वैशाख",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "चित्रा",
    sunrise: "05:30 AM",
    sunset: "07:40 PM",
    event: true,
    url: "/other/buddha.png"
  },
  {
    date: "2025-05-13",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "स्वाति",
    sunrise: "05:29 AM",
    sunset: "07:41 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-14",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "विशाखा",
    sunrise: "05:28 AM",
    sunset: "07:42 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-15",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "अनुराधा",
    sunrise: "05:27 AM",
    sunset: "07:43 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-16",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "ज्येष्ठा",
    sunrise: "05:26 AM",
    sunset: "07:44 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-17",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "मूल",
    sunrise: "05:25 AM",
    sunset: "07:45 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-18",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "05:24 AM",
    sunset: "07:46 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-19",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "05:23 AM",
    sunset: "07:47 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-20",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "श्रवण",
    sunrise: "05:22 AM",
    sunset: "07:48 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-21",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "धनिष्ठा",
    sunrise: "05:21 AM",
    sunset: "07:49 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-22",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "शतभिषा",
    sunrise: "05:20 AM",
    sunset: "07:50 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-23",
    title: "Apara Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "05:19 AM",
    sunset: "07:51 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-05-24",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "05:18 AM",
    sunset: "07:52 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-25",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "रेवती",
    sunrise: "05:17 AM",
    sunset: "07:53 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-26",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "अश्विनी",
    sunrise: "05:16 AM",
    sunset: "07:54 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-27",
    title: "Jyeshtha Amavasya",
    description: "No Moon Day",
    hinduMonth: "ज्येष्ठ",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "भरणी",
    sunrise: "05:15 AM",
    sunset: "07:55 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-05-28",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "मृगशिरा",
    sunrise: "05:14 AM",
    sunset: "07:56 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-29",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "आर्द्रा",
    sunrise: "05:13 AM",
    sunset: "07:57 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-30",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "पुनर्वसु",
    sunrise: "05:12 AM",
    sunset: "07:58 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-05-31",
    title: "",
    description: "",
    hinduMonth: "ज्येष्ठ",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "पुष्य",
    sunrise: "05:11 AM",
    sunset: "07:59 PM",
    event: false,
    url: ""
  }
];