export const november = [
  {
    date: "2025-11-01",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "रेवती",
    sunrise: "06:12 AM",
    sunset: "06:31 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-02",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "अश्विनी",
    sunrise: "06:12 AM",
    sunset: "06:30 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-03",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "भरणी",
    sunrise: "06:13 AM",
    sunset: "06:29 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-04",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "कृत्तिका",
    sunrise: "06:13 AM",
    sunset: "06:28 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-05",
    title: "Rama Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "रोहिणी",
    sunrise: "06:14 AM",
    sunset: "06:28 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-11-06",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "मृगशिरा",
    sunrise: "06:14 AM",
    sunset: "06:27 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-07",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "आर्द्रा",
    sunrise: "06:15 AM",
    sunset: "06:26 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-08",
    title: "Kartika Purnima",
    description: "Full Moon Day",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "पुनर्वसु",
    sunrise: "06:15 AM",
    sunset: "06:25 PM",
    event: true,
    url: "/other/fullmoon.png"
  },
  {
    date: "2025-11-09",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पुष्य",
    sunrise: "06:16 AM",
    sunset: "06:25 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-10",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "आश्लेषा",
    sunrise: "06:16 AM",
    sunset: "06:24 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-11",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "मघा",
    sunrise: "06:17 AM",
    sunset: "06:23 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-12",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "06:17 AM",
    sunset: "06:23 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-13",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "06:18 AM",
    sunset: "06:22 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-14",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "हस्त",
    sunrise: "06:18 AM",
    sunset: "06:22 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-15",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "चित्रा",
    sunrise: "06:19 AM",
    sunset: "06:21 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-16",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "स्वाति",
    sunrise: "06:19 AM",
    sunset: "06:21 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-17",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "विशाखा",
    sunrise: "06:20 AM",
    sunset: "06:20 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-18",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "अनुराधा",
    sunrise: "06:20 AM",
    sunset: "06:20 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-19",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "ज्येष्ठा",
    sunrise: "06:21 AM",
    sunset: "06:19 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-20",
    title: "Utapanna Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "मूल",
    sunrise: "06:21 AM",
    sunset: "06:19 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-11-21",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "06:22 AM",
    sunset: "06:19 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-22",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "06:22 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-23",
    title: "Margashirsha Amavasya",
    description: "No Moon Day",
    hinduMonth: "मार्गशीर्ष",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "श्रवण",
    sunrise: "06:23 AM",
    sunset: "06:18 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-11-24",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "धनिष्ठा",
    sunrise: "06:23 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-25",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "शतभिषा",
    sunrise: "06:24 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-26",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "06:24 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-27",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "06:25 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-28",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "रेवती",
    sunrise: "06:25 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-29",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "अश्विनी",
    sunrise: "06:26 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-11-30",
    title: "",
    description: "",
    hinduMonth: "मार्गशीर्ष",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "भरणी",
    sunrise: "06:26 AM",
    sunset: "06:18 PM",
    event: false,
    url: ""
  }
];