export const october = [
  {
    date: "2025-10-01",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "धनिष्ठा",
    sunrise: "05:56 AM",
    sunset: "07:02 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-02",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "शतभिषा",
    sunrise: "05:57 AM",
    sunset: "07:01 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-03",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "05:57 AM",
    sunset: "07:00 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-04",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "05:58 AM",
    sunset: "06:59 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-05",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "रेवती",
    sunrise: "05:58 AM",
    sunset: "06:58 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-06",
    title: "Indira Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "अश्विनी",
    sunrise: "05:59 AM",
    sunset: "06:57 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-10-07",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "भरणी",
    sunrise: "05:59 AM",
    sunset: "06:56 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-08",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "कृत्तिका",
    sunrise: "06:00 AM",
    sunset: "06:55 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-09",
    title: "Ashwina Purnima (Sharad Purnima)",
    description: "Full Moon Day, Sharad Purnima",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "रोहिणी",
    sunrise: "06:00 AM",
    sunset: "06:54 PM",
    event: true,
    url: "/other/fullmoon.png"
  },
  {
    date: "2025-10-10",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "मृगशिरा",
    sunrise: "06:01 AM",
    sunset: "06:53 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-11",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "आर्द्रा",
    sunrise: "06:01 AM",
    sunset: "06:52 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-12",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "पुनर्वसु",
    sunrise: "06:02 AM",
    sunset: "06:51 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-13",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "पुष्य",
    sunrise: "06:02 AM",
    sunset: "06:50 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-14",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "आश्लेषा",
    sunrise: "06:03 AM",
    sunset: "06:49 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-15",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "मघा",
    sunrise: "06:03 AM",
    sunset: "06:48 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-16",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "06:04 AM",
    sunset: "06:47 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-17",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "06:04 AM",
    sunset: "06:46 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-18",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "हस्त",
    sunrise: "06:05 AM",
    sunset: "06:45 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-19",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "चित्रा",
    sunrise: "06:05 AM",
    sunset: "06:44 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-20",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "स्वाति",
    sunrise: "06:06 AM",
    sunset: "06:43 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-21",
    title: "Papankusha Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "विशाखा",
    sunrise: "06:06 AM",
    sunset: "06:42 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-10-22",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "अनुराधा",
    sunrise: "06:07 AM",
    sunset: "06:41 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-23",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "ज्येष्ठा",
    sunrise: "06:07 AM",
    sunset: "06:40 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-24",
    title: "Kartika Amavasya (Diwali)",
    description: "No Moon Day, Diwali",
    hinduMonth: "कार्तिक",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "मूल",
    sunrise: "06:08 AM",
    sunset: "06:39 PM",
    event: true,
    url: "/other/diwali.png"
  },
  {
    date: "2025-10-25",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "06:08 AM",
    sunset: "06:38 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-26",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "06:09 AM",
    sunset: "06:37 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-27",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "श्रवण",
    sunrise: "06:09 AM",
    sunset: "06:36 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-28",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "धनिष्ठा",
    sunrise: "06:10 AM",
    sunset: "06:35 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-29",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "शतभिषा",
    sunrise: "06:10 AM",
    sunset: "06:34 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-30",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "06:11 AM",
    sunset: "06:33 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-10-31",
    title: "",
    description: "",
    hinduMonth: "कार्तिक",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "06:11 AM",
    sunset: "06:32 PM",
    event: false,
    url: ""
  }
];