export const september = [
  {
    date: "2025-09-01",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "सप्तमी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "05:41 AM",
    sunset: "07:32 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-02",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "अष्टमी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "05:42 AM",
    sunset: "07:31 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-03",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "नवमी",
    nakshatra: "श्रवण",
    sunrise: "05:42 AM",
    sunset: "07:30 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-04",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "दशमी",
    nakshatra: "धनिष्ठा",
    sunrise: "05:43 AM",
    sunset: "07:29 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-05",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "एकादशी",
    nakshatra: "शतभिषा",
    sunrise: "05:43 AM",
    sunset: "07:28 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-06",
    title: "Padmini Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वादशी",
    nakshatra: "पूर्वभाद्रपद",
    sunrise: "05:44 AM",
    sunset: "07:27 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-09-07",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "उत्तरभाद्रपद",
    sunrise: "05:44 AM",
    sunset: "07:26 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-08",
    title: "",
    description: "",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "रेवती",
    sunrise: "05:45 AM",
    sunset: "07:25 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-09",
    title: "Bhadrapada Purnima",
    description: "Full Moon Day",
    hinduMonth: "भाद्रपद",
    paksh: "शुक्ल पक्ष",
    tithi: "पूर्णिमा",
    nakshatra: "अश्विनी",
    sunrise: "05:45 AM",
    sunset: "07:24 PM",
    event: true,
    url: "/other/fullmoon.png"
  },
  {
    date: "2025-09-10",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "भरणी",
    sunrise: "05:46 AM",
    sunset: "07:23 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-11",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वितीया",
    nakshatra: "कृत्तिका",
    sunrise: "05:46 AM",
    sunset: "07:22 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-12",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "तृतीया",
    nakshatra: "रोहिणी",
    sunrise: "05:47 AM",
    sunset: "07:21 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-13",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "मृगशिरा",
    sunrise: "05:47 AM",
    sunset: "07:20 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-14",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "पंचमी",
    nakshatra: "आर्द्रा",
    sunrise: "05:48 AM",
    sunset: "07:19 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-15",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "षष्ठी",
    nakshatra: "पुनर्वसु",
    sunrise: "05:48 AM",
    sunset: "07:18 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-16",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "सप्तमी",
    nakshatra: "पुष्य",
    sunrise: "05:49 AM",
    sunset: "07:17 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-17",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "अष्टमी",
    nakshatra: "आश्लेषा",
    sunrise: "05:49 AM",
    sunset: "07:16 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-18",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "नवमी",
    nakshatra: "मघा",
    sunrise: "05:50 AM",
    sunset: "07:15 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-19",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "दशमी",
    nakshatra: "पूर्वा फाल्गुनी",
    sunrise: "05:50 AM",
    sunset: "07:14 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-20",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "एकादशी",
    nakshatra: "उत्तर फाल्गुनी",
    sunrise: "05:51 AM",
    sunset: "07:13 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-21",
    title: "Parama Ekadashi",
    description: "Ekadashi Vrat",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "द्वादशी",
    nakshatra: "हस्त",
    sunrise: "05:51 AM",
    sunset: "07:12 PM",
    event: true,
    url: "/other/ekadashi.png"
  },
  {
    date: "2025-09-22",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "त्रयोदशी",
    nakshatra: "चित्रा",
    sunrise: "05:52 AM",
    sunset: "07:11 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-23",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "चतुर्दशी",
    nakshatra: "स्वाति",
    sunrise: "05:52 AM",
    sunset: "07:10 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-24",
    title: "Ashwina Amavasya",
    description: "No Moon Day",
    hinduMonth: "आश्विन",
    paksh: "कृष्ण पक्ष",
    tithi: "अमावस्या",
    nakshatra: "विशाखा",
    sunrise: "05:53 AM",
    sunset: "07:09 PM",
    event: true,
    url: "/other/nomoon.png"
  },
  {
    date: "2025-09-25",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "प्रतिपदा",
    nakshatra: "अनुराधा",
    sunrise: "05:53 AM",
    sunset: "07:08 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-26",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "द्वितीया",
    nakshatra: "ज्येष्ठा",
    sunrise: "05:54 AM",
    sunset: "07:07 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-27",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "तृतीया",
    nakshatra: "मूल",
    sunrise: "05:54 AM",
    sunset: "07:06 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-28",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "चतुर्थी",
    nakshatra: "पूर्वाषाढ़ा",
    sunrise: "05:55 AM",
    sunset: "07:05 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-29",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "पंचमी",
    nakshatra: "उत्तराषाढ़ा",
    sunrise: "05:55 AM",
    sunset: "07:04 PM",
    event: false,
    url: ""
  },
  {
    date: "2025-09-30",
    title: "",
    description: "",
    hinduMonth: "आश्विन",
    paksh: "शुक्ल पक्ष",
    tithi: "षष्ठी",
    nakshatra: "श्रवण",
    sunrise: "05:56 AM",
    sunset: "07:03 PM",
    event: false,
    url: ""
  }
];